### ISSUE TITLE
Project Submission: JackCS

### ISSUE THREAD

**Issue by Beyley** [SilkCommunity/SilkCommunity#5]
## Basic Information

- Project Name: JackCS
- Current Maintainers (incl. Discord names/discriminators & GitHub accounts): PoltixeTheDerg#9088 (discord) and `Beyley` (gh)
- Current License: MIT
- Silk.NET Libraries Used (e.g. Windowing, Input, OpenGL, Vulkan, etc): uses BuildTools and SilkTouch
- Other Used Libraries: has a submodule of `jack2` to access the headers
- GitHub Link: https://github.com/Beyley/JackCS

## Description

[Jack](https://jackaudio.org/) bindings for C#, allowing access to simple cross platform low latency audio

**Comment by Perksey** [comment]
The Silk.NET maintainers have reviewed this submission and are happy to bring this project into the Silk.NET Community group!

Please get in touch with us via Discord to work through the following steps:
- [x] Adopt the Contributor Covenant Code of Conduct
- [x] Join the Silk.NET Discord Server and get the Community Project Maintainer role
- [x] Transfer the repository into the SilkCommunity GitHub organisation
