### ISSUE TITLE
Project Submission: 

### ISSUE THREAD

**Issue by CalvinWilkinson** [SilkCommunity/SilkCommunity#6]
## Basic Information

- Project Name:  Velaptor
- Website: https://docs.velaptor.io
- Current Maintainers (incl. Discord names/discriminators & GitHub accounts):
  - Github:
    - [Calvin Wilkinson](https://github.com/CalvinWilkinson)
    - [Kristen Wilkinson](https://github.com/kselena)
  - Twitter:
    - [KDCoder](https://twitter.com/KDCoder) - Main development
    - [KSWilky](https://twitter.com/kswilky) - Documentation, simple config maintenance, and project management
  - Discord:
    - KinsonDigital#6819
    - kselena#4202
- Current License:  MIT
- Silk.NET Libraries Used (e.g. Windowing, Input, OpenGL, Vulkan, etc):
  - Silk.NET - Windowing, input, opengl are all used. 
- Other Used Libraries: 
- GitHub Link: [Velaptor](https://github.com/KinsonDigital/Velaptor)

## Description

**what does it do?**
Velaptor is a 2D game development framework, written in C# for C#.  It is also going to be geared to creating simple UI applications using UI controls.  So it could be used for more than just games!!

**who is it for?**
It is made for anybody wanting to create cross-platform

**how far along in development is it?**
It is currently in preview and approaching version v1.0.0!!  

**are the main features it advertises stable and ready for use?**
The features it currently has are quite stable.  Most of the future work until preview is to implement more features as well as code cleanup and maintence.  It is quite stable because I maintain loosely coupled code in combination with very high code coverage and lot's of manual testing by maintaining a custom manual testing application.

**Comment by HurricanKai** [comment]
Please add GitHub handles to the maintainer Information, haven't been able to easily find them.

**Comment by CalvinWilkinson** [comment]
@HurricanKai Sorry about that.  I don't know how I missed that. :)

**Comment by Perksey** [comment]
The Silk.NET maintainers have reviewed this submission and are happy to bring this project into the Silk.NET Community group!

Please get in touch with us via Discord to work through the following steps:
- [ ] Adopt the Contributor Covenant Code of Conduct
    - This involves creating a CODE_OF_CONDUCT.md file with [these contents](https://github.com/SilkCommunity/SilkCommunity/blob/main/CODE_OF_CONDUCT.md)
- [x] Join the Silk.NET Discord Server and get the Community Project Maintainer role
    - This will be given to you by a Silk.NET maintainer. If you are not known by a Silk.NET maintainer in the Discord server, please DM a maintainer and we'll verify that you own the project in question.
    - A community project channel in the discord server will also be created.
- [ ] Transfer the repository into the SilkCommunity GitHub organisation
    - This involves creating a project transfer request to the following username: silkdotnet
    - We will then transfer it into SilkCommunity.

**Comment by Perksey** [comment]
It seems `kselena#4202` is not in the Discord server.

From the README:
> You will need to use Discord and join the Silk.NET Discord Server so that we can maintain contact with you, ideally providing an alternative contact method (such as an email address) in case we can't
> You will need to remain contactable via Discord in the first instance, and via the alternative method provided if all else fails.

Given one maintainer is already in the Discord, there is no need for them to join so long as we have an alternate contact method. (but it's probably easier to join the server)

**Comment by CalvinWilkinson** [comment]
@Perksey Thanks for the acceptance!! Unfortunately, I miss understood some of what would be going on with the project such as transferring the project to a new organization.  This is my fault and I apologize for wasting your time.

Due to the required changes, they do not meet my personal goals and plans so I will respectfully decline.

Of course, this is not personal and has no bearing on my opinion of SILK or the SILK community, how you guys run things, or on anyone in the community.  You guys have been fantastic and I love the work you guys are doing.

Again, thanks for your time!!  🙂

**Comment by Perksey** [comment]
No worries! We've tried to keep it as hands-off as possible while also aggregating useful projects under a single umbrella, and emphasise in the README that all projects keep all admin rights, copyright, autonomy, and monetisation rights; but we understand this still may not be appropriate for everyone. Feel free to reopen if you reconsider!

**Comment by CalvinWilkinson** [comment]
> No worries! We've tried to keep it as hands-off as possible while also aggregating useful projects under a single umbrella, and emphasise in the README that all projects keep all admin rights, copyright, autonomy, and monetisation rights; but we understand this still may not be appropriate for everyone. Feel free to reopen if you reconsider!

Thanks @Perksey!!  Greatly appreciated and keep up the great work. 🤘🏻
